### ISSUE TITLE
I think that the browser.xul no longer exists in Firefox 69.0.

### ISSUE THREAD

**Issue by gaveitatry02** [nilcons/firefox-hacks#3]
Hi Errge.  I could use your help again.  A while back, I used your instructions to make changes to the browser.xul.  I believe that I was using Firefox 68.0 at the time, and the browser.xul changes worked.  I was reluctant to update Firefox for the past many months, but I finally updated to Firefox 69.0 today.  Today, I tried extracting the omni.ja and I could no longer find a browser.xul.  My guess is that they got rid of the browser.xul and they put the key ids and commands in some other file.  Could you help me find out what the new file is so I can go back to editing the shortcut keys for Firefox?  I hope that you will help me.  Thank you.

**Comment by gaveitatry02** [comment]
Nevermind.  I think that i found it.  They call it browser.xhtml now.

**Comment by Hochiss** [comment]
@gaveitatry02 Do you know what's the setting file in Windows?  or any hints? 

thanks!
